/**
 * @license Copyright (c) 2003-2018, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
 */

/* exported CKBUILDER_CONFIG */

var CKBUILDER_CONFIG = {
	skin: 'moono-lisa',
	ignore: [
		'bender.js',
		'bender.ci.js',
		'.bender',
		'bender-err.log',
		'bender-out.log',
		'.travis.yml',
		'dev',
		'docs',
		'.DS_Store',
		'.editorconfig',
		'.gitignore',
		'.gitattributes',
		'gruntfile.js',
		'.idea',
		'.jscsrc',
		'.jshintignore',
		'.jshintrc',
		'less',
		'.mailmap',
		'node_modules',
		'package.json',
		'README.md',
		'tests'
	],
	plugins: {
	basicstyles: 1,
	blockquote: 1,
	dialogui: 1,
	dialog: 1,
	notification: 1,
	button: 1,
	toolbar: 1,
	clipboard: 1,
	panel: 1,
	floatpanel: 1,
	menu: 1,
	contextmenu: 1,
	enterkey: 1,
	entities: 1,
	popup: 1,
	filetools: 1,
	filebrowser: 1,
	floatingspace:1 ,
	listblock:1 ,
	richcombo:1 ,
	format:1 ,
	horizontalrule:1 ,
	htmlwriter:1 ,
	wysiwygarea:1 ,
	image:1 ,
	indent:1 ,
	indentlist:1 ,
	fakeobjects:1 ,
	link:1 ,
	list:1 ,
	magicline:1 ,
	maximize:1 ,
	pastetext:1 ,
	pastefromword:1 ,
	removeformat:1 ,
	showborders: 1,
	sourcearea: 1,
	specialchar: 1,
	menubutton: 1,
	scayt: 1,
	stylescombo: 1,
	tab: 1,
	table: 1,
	tabletools: 1,
	tableselection: 1,
	undo: 1,
	lineutils: 1,
	widgetselection: 1,
	widget: 1,
	notificationaggregator: 1,
	uploadwidget: 1,
	uploadimage: 1,
	wsc: 1,
	codesnippet: 1,
	find: 1,
	autolink: 1,
	autoembed: 1,
	balloonpanel: 1,
	balloontoolbar: 1,
	chart: 1,
	colordialog: 1,
	docprops: 1,
	imagebase: 1,
	xml: 1,
	ajax: 1,
	emojione: 1,
	image2: 1,
	eqneditor: 1,
	font: 1,
	html5video: 1,
	// imageuploader: 1,
	indentblock: 1,
	wordcount: 1,
	uicolor: 1,
	toc: 1,
	SimpleLink: 1,
	textindent: 1,
	onchange: 1,
	textselection: 1
	}
};
